import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Providers } from "../lib/auth/auth.provider"

import { ThemeProvider } from "./themeProvider"
import BootcampSettings from "./components/settings"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Code Bootcamp",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
           <ThemeProvider>
              <main>
                {children}
              </main>
              <BootcampSettings />
           </ThemeProvider>=
        </Providers>
      </body>
    </html>
  );
}